"""empty message

Revision ID: 62be0341870f
Revises: 91e88056f4c9
Create Date: 2022-05-09 19:29:16.304997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62be0341870f'
down_revision = '91e88056f4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('eye_color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'eye_color')
    # ### end Alembic commands ###
